// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	BaseFeePerGas        string               `protobuf:"bytes,1,opt,name=BaseFeePerGas,proto3" json:"BaseFeePerGas,omitempty"`
	BlockNumber          string               `protobuf:"bytes,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	Difficulty           string               `protobuf:"bytes,3,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	GasLimit             string               `protobuf:"bytes,4,opt,name=GasLimit,proto3" json:"GasLimit,omitempty"`
	GasUsed              string               `protobuf:"bytes,5,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	Hash                 string               `protobuf:"bytes,6,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Miner                string               `protobuf:"bytes,7,opt,name=Miner,proto3" json:"Miner,omitempty"`
	ParentHash           string               `protobuf:"bytes,8,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	Timestamp            uint64               `protobuf:"varint,9,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Transactions         []*Block_Transaction `protobuf:"bytes,10,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	Uncles               []string             `protobuf:"bytes,11,rep,name=Uncles,proto3" json:"Uncles,omitempty"`
	Withdrawals          []string             `protobuf:"bytes,12,rep,name=Withdrawals,proto3" json:"Withdrawals,omitempty"`
	Number               string               `protobuf:"bytes,13,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBaseFeePerGas() string {
	if m != nil {
		return m.BaseFeePerGas
	}
	return ""
}

func (m *Block) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Block) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *Block) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *Block) GetGasUsed() string {
	if m != nil {
		return m.GasUsed
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func (m *Block) GetParentHash() string {
	if m != nil {
		return m.ParentHash
	}
	return ""
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetTransactions() []*Block_Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetUncles() []string {
	if m != nil {
		return m.Uncles
	}
	return nil
}

func (m *Block) GetWithdrawals() []string {
	if m != nil {
		return m.Withdrawals
	}
	return nil
}

func (m *Block) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type Block_Transaction struct {
	BlockHash            string   `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockNumber          string   `protobuf:"bytes,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	Gas                  string   `protobuf:"bytes,4,opt,name=Gas,proto3" json:"Gas,omitempty"`
	GasPrice             string   `protobuf:"bytes,5,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	GasUsed              string   `protobuf:"bytes,6,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	HasToken             bool     `protobuf:"varint,7,opt,name=HasToken,proto3" json:"HasToken,omitempty"`
	Hash                 string   `protobuf:"bytes,8,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Input                string   `protobuf:"bytes,9,opt,name=Input,proto3" json:"Input,omitempty"`
	IsError              bool     `protobuf:"varint,10,opt,name=IsError,proto3" json:"IsError,omitempty"`
	MaxFeePerGas         string   `protobuf:"bytes,11,opt,name=MaxFeePerGas,proto3" json:"MaxFeePerGas,omitempty"`
	MaxPriorityFeePerGas string   `protobuf:"bytes,12,opt,name=MaxPriorityFeePerGas,proto3" json:"MaxPriorityFeePerGas,omitempty"`
	Nonce                uint64   `protobuf:"varint,13,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Timestamp            uint64   `protobuf:"varint,14,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	To                   string   `protobuf:"bytes,15,opt,name=To,proto3" json:"To,omitempty"`
	TransactionIndex     string   `protobuf:"bytes,16,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	TransactionType      string   `protobuf:"bytes,17,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	Value                string   `protobuf:"bytes,18,opt,name=Value,proto3" json:"Value,omitempty"`
	Message              string   `protobuf:"bytes,19,opt,name=Message,proto3" json:"Message,omitempty"`
	V                    string   `protobuf:"bytes,20,opt,name=V,proto3" json:"V,omitempty"`
	R                    string   `protobuf:"bytes,21,opt,name=R,proto3" json:"R,omitempty"`
	S                    string   `protobuf:"bytes,22,opt,name=S,proto3" json:"S,omitempty"`
	YParity              string   `protobuf:"bytes,23,opt,name=YParity,proto3" json:"YParity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block_Transaction) Reset()         { *m = Block_Transaction{} }
func (m *Block_Transaction) String() string { return proto.CompactTextString(m) }
func (*Block_Transaction) ProtoMessage()    {}
func (*Block_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0, 0}
}

func (m *Block_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block_Transaction.Unmarshal(m, b)
}
func (m *Block_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block_Transaction.Marshal(b, m, deterministic)
}
func (m *Block_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block_Transaction.Merge(m, src)
}
func (m *Block_Transaction) XXX_Size() int {
	return xxx_messageInfo_Block_Transaction.Size(m)
}
func (m *Block_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Block_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Block_Transaction proto.InternalMessageInfo

func (m *Block_Transaction) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Block_Transaction) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Block_Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Block_Transaction) GetGas() string {
	if m != nil {
		return m.Gas
	}
	return ""
}

func (m *Block_Transaction) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Block_Transaction) GetGasUsed() string {
	if m != nil {
		return m.GasUsed
	}
	return ""
}

func (m *Block_Transaction) GetHasToken() bool {
	if m != nil {
		return m.HasToken
	}
	return false
}

func (m *Block_Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block_Transaction) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Block_Transaction) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *Block_Transaction) GetMaxFeePerGas() string {
	if m != nil {
		return m.MaxFeePerGas
	}
	return ""
}

func (m *Block_Transaction) GetMaxPriorityFeePerGas() string {
	if m != nil {
		return m.MaxPriorityFeePerGas
	}
	return ""
}

func (m *Block_Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block_Transaction) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block_Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Block_Transaction) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

func (m *Block_Transaction) GetTransactionType() string {
	if m != nil {
		return m.TransactionType
	}
	return ""
}

func (m *Block_Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Block_Transaction) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Block_Transaction) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *Block_Transaction) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Block_Transaction) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Block_Transaction) GetYParity() string {
	if m != nil {
		return m.YParity
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "protobuf.Block")
	proto.RegisterType((*Block_Transaction)(nil), "protobuf.Block.Transaction")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x86, 0x05, 0x04, 0x1a, 0x4e, 0x68, 0xcb, 0x3c, 0xd6, 0x1d, 0xb1, 0x69, 0x42, 0xd5, 0x2e,
	0xd0, 0x2e, 0xa8, 0xd4, 0x3d, 0xc0, 0x24, 0xb4, 0x95, 0x22, 0x8d, 0x0a, 0xa5, 0x29, 0xd3, 0x76,
	0x67, 0x82, 0x59, 0x2d, 0x20, 0x46, 0x76, 0xd0, 0xe0, 0x35, 0xf6, 0xa2, 0x7b, 0x85, 0xc9, 0xc7,
	0x01, 0x92, 0x6e, 0x17, 0xbd, 0x8a, 0xbf, 0xff, 0xfc, 0x39, 0xb6, 0xcf, 0x6f, 0x08, 0xa6, 0x4b,
	0x15, 0x2f, 0x7a, 0x6b, 0xad, 0x52, 0xc5, 0x7c, 0xfa, 0x4c, 0x37, 0xf3, 0xcb, 0xdf, 0x3e, 0x54,
	0xfb, 0xb6, 0xc2, 0xde, 0xc3, 0x69, 0x9f, 0x1b, 0x71, 0x23, 0xc4, 0x58, 0xe8, 0x01, 0x37, 0x58,
	0xea, 0x94, 0xba, 0xf5, 0xb0, 0x28, 0xb2, 0x0e, 0x04, 0x64, 0xbf, 0xdb, 0xac, 0xa6, 0x42, 0x63,
	0x99, 0x3c, 0x79, 0x89, 0xbd, 0x03, 0xf8, 0x2c, 0xe7, 0x73, 0x19, 0x6f, 0x96, 0xe9, 0x0e, 0x2b,
	0x64, 0xc8, 0x29, 0xac, 0x0d, 0xfe, 0x80, 0x9b, 0xaf, 0x72, 0x25, 0x53, 0xf4, 0xa8, 0x7a, 0x60,
	0x86, 0x70, 0x32, 0xe0, 0xe6, 0xc1, 0x88, 0x19, 0x56, 0xa9, 0xb4, 0x47, 0xc6, 0xc0, 0xbb, 0xe5,
	0xe6, 0x11, 0x6b, 0x24, 0xd3, 0x9a, 0xb5, 0xa0, 0x3a, 0x92, 0x89, 0xd0, 0x78, 0x42, 0xa2, 0x03,
	0xbb, 0xff, 0x98, 0x6b, 0x91, 0xa4, 0xe4, 0xf7, 0xdd, 0xfe, 0x47, 0x85, 0xbd, 0x85, 0x7a, 0x24,
	0x57, 0xc2, 0xa4, 0x7c, 0xb5, 0xc6, 0x7a, 0xa7, 0xd4, 0xf5, 0xc2, 0xa3, 0xc0, 0x3e, 0x41, 0x23,
	0xd2, 0x3c, 0x31, 0x3c, 0x4e, 0xa5, 0x4a, 0x0c, 0x42, 0xa7, 0xd2, 0x0d, 0xae, 0xdf, 0xf4, 0xf6,
	0x03, 0xeb, 0xd1, 0x55, 0x7b, 0x39, 0x4f, 0x58, 0xf8, 0x81, 0x5d, 0x40, 0xed, 0x21, 0x89, 0x97,
	0xc2, 0x60, 0xd0, 0xa9, 0x74, 0xeb, 0x61, 0x46, 0x76, 0x70, 0xdf, 0x64, 0xfa, 0x38, 0xd3, 0xfc,
	0x17, 0x5f, 0x1a, 0x6c, 0x50, 0x31, 0x2f, 0xd9, 0x3f, 0xb3, 0xa9, 0x9e, 0xd2, 0xa1, 0x33, 0x6a,
	0xff, 0xf1, 0x20, 0xc8, 0x6d, 0x61, 0x2f, 0x40, 0x87, 0xa0, 0xfb, 0xb9, 0x90, 0x8e, 0xc2, 0x33,
	0x02, 0x62, 0xe0, 0xdd, 0x68, 0xb5, 0xca, 0xa2, 0xa1, 0x35, 0x6b, 0x42, 0xc5, 0x46, 0xee, 0xf2,
	0xb0, 0xcb, 0x2c, 0xa6, 0xb1, 0x96, 0xb1, 0xc8, 0xb2, 0x38, 0x70, 0x3e, 0xa6, 0x5a, 0x31, 0xa6,
	0x36, 0xf8, 0xb7, 0xdc, 0x44, 0x6a, 0x21, 0x12, 0x4a, 0xc5, 0x0f, 0x0f, 0x7c, 0x88, 0xd0, 0x2f,
	0x46, 0x38, 0x4c, 0xd6, 0x9b, 0x94, 0x82, 0xa8, 0x87, 0x0e, 0x6c, 0xff, 0xa1, 0xf9, 0xa2, 0xb5,
	0xd2, 0x08, 0xd4, 0x64, 0x8f, 0xec, 0x12, 0x1a, 0x23, 0xbe, 0x3d, 0xbe, 0xd1, 0x80, 0x7e, 0x2b,
	0x68, 0xec, 0x1a, 0x5a, 0x23, 0xbe, 0x1d, 0x6b, 0xa9, 0xb4, 0x4c, 0x77, 0x47, 0x6f, 0x83, 0xbc,
	0xff, 0xad, 0xd9, 0x73, 0xdc, 0xa9, 0x24, 0x16, 0x34, 0x7a, 0x2f, 0x74, 0x50, 0x7c, 0x2a, 0x67,
	0x4f, 0x9f, 0xca, 0x19, 0x94, 0x23, 0x85, 0xe7, 0xd4, 0xb5, 0x1c, 0x29, 0xf6, 0x01, 0x9a, 0xb9,
	0x98, 0x86, 0xc9, 0x4c, 0x6c, 0xb1, 0x49, 0xd5, 0x7f, 0x74, 0xd6, 0x85, 0xf3, 0x9c, 0x16, 0xed,
	0xd6, 0x02, 0x5f, 0x90, 0xf5, 0xa9, 0x6c, 0x4f, 0x36, 0xe1, 0xcb, 0x8d, 0x40, 0xe6, 0x26, 0x44,
	0x60, 0x27, 0x34, 0x12, 0xc6, 0xf0, 0x9f, 0x02, 0x5f, 0xba, 0x04, 0x32, 0x64, 0x0d, 0x28, 0x4d,
	0xb0, 0x45, 0x5a, 0x69, 0x62, 0x29, 0xc4, 0x57, 0x8e, 0x42, 0x4b, 0xf7, 0x78, 0xe1, 0xe8, 0xde,
	0xf6, 0xf8, 0x3e, 0xe6, 0x76, 0x0e, 0xf8, 0xda, 0xf5, 0xc8, 0xb0, 0xdf, 0xfa, 0xc1, 0x8c, 0x8e,
	0xaf, 0x16, 0x7c, 0xbe, 0xe0, 0x57, 0xfb, 0x97, 0x3f, 0xad, 0xd1, 0xea, 0xe3, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3c, 0x77, 0x3b, 0xde, 0x4a, 0x04, 0x00, 0x00,
}
