// Code generated by protoc-gen-go. DO NOT EDIT.
// source: receipt.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Receipt struct {
	BlockHash            string         `protobuf:"bytes,1,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockNumber          string         `protobuf:"bytes,2,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	ContractAddress      string         `protobuf:"bytes,3,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"`
	CumulativeGasUsed    string         `protobuf:"bytes,4,opt,name=CumulativeGasUsed,proto3" json:"CumulativeGasUsed,omitempty"`
	EffectiveGasPrice    string         `protobuf:"bytes,5,opt,name=EffectiveGasPrice,proto3" json:"EffectiveGasPrice,omitempty"`
	From                 string         `protobuf:"bytes,6,opt,name=From,proto3" json:"From,omitempty"`
	GasUsed              string         `protobuf:"bytes,7,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	IsError              bool           `protobuf:"varint,8,opt,name=IsError,proto3" json:"IsError,omitempty"`
	Logs                 []*Receipt_Log `protobuf:"bytes,9,rep,name=Logs,proto3" json:"Logs,omitempty"`
	Status               string         `protobuf:"bytes,10,opt,name=Status,proto3" json:"Status,omitempty"`
	To                   string         `protobuf:"bytes,11,opt,name=To,proto3" json:"To,omitempty"`
	TransactionHash      string         `protobuf:"bytes,12,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	TransactionIndex     string         `protobuf:"bytes,13,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_ace1d6eb38fad2c8, []int{0}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Receipt) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Receipt) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Receipt) GetCumulativeGasUsed() string {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return ""
}

func (m *Receipt) GetEffectiveGasPrice() string {
	if m != nil {
		return m.EffectiveGasPrice
	}
	return ""
}

func (m *Receipt) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Receipt) GetGasUsed() string {
	if m != nil {
		return m.GasUsed
	}
	return ""
}

func (m *Receipt) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *Receipt) GetLogs() []*Receipt_Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Receipt) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Receipt) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Receipt) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Receipt) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

type Receipt_Log struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	BlockNumber          string   `protobuf:"bytes,3,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	LogIndex             string   `protobuf:"bytes,5,opt,name=LogIndex,proto3" json:"LogIndex,omitempty"`
	Timestamp            uint64   `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Topics               []string `protobuf:"bytes,7,rep,name=Topics,proto3" json:"Topics,omitempty"`
	TransactionHash      string   `protobuf:"bytes,8,opt,name=TransactionHash,proto3" json:"TransactionHash,omitempty"`
	TransactionIndex     string   `protobuf:"bytes,9,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt_Log) Reset()         { *m = Receipt_Log{} }
func (m *Receipt_Log) String() string { return proto.CompactTextString(m) }
func (*Receipt_Log) ProtoMessage()    {}
func (*Receipt_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_ace1d6eb38fad2c8, []int{0, 0}
}

func (m *Receipt_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt_Log.Unmarshal(m, b)
}
func (m *Receipt_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt_Log.Marshal(b, m, deterministic)
}
func (m *Receipt_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt_Log.Merge(m, src)
}
func (m *Receipt_Log) XXX_Size() int {
	return xxx_messageInfo_Receipt_Log.Size(m)
}
func (m *Receipt_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt_Log proto.InternalMessageInfo

func (m *Receipt_Log) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Receipt_Log) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Receipt_Log) GetBlockNumber() string {
	if m != nil {
		return m.BlockNumber
	}
	return ""
}

func (m *Receipt_Log) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Receipt_Log) GetLogIndex() string {
	if m != nil {
		return m.LogIndex
	}
	return ""
}

func (m *Receipt_Log) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Receipt_Log) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Receipt_Log) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *Receipt_Log) GetTransactionIndex() string {
	if m != nil {
		return m.TransactionIndex
	}
	return ""
}

func init() {
	proto.RegisterType((*Receipt)(nil), "protobuf.Receipt")
	proto.RegisterType((*Receipt_Log)(nil), "protobuf.Receipt.Log")
}

func init() { proto.RegisterFile("receipt.proto", fileDescriptor_ace1d6eb38fad2c8) }

var fileDescriptor_ace1d6eb38fad2c8 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xdd, 0xce, 0x93, 0x30,
	0x18, 0xc7, 0x33, 0xe0, 0x1d, 0xf0, 0xcc, 0xd7, 0x8f, 0x46, 0x4d, 0xb3, 0x78, 0x40, 0x3c, 0x42,
	0x63, 0x58, 0xa2, 0x57, 0xe0, 0xe6, 0xd4, 0x25, 0xc4, 0x18, 0xc4, 0x13, 0xcf, 0xba, 0x52, 0x90,
	0x6c, 0x50, 0xd2, 0x16, 0xe3, 0xbd, 0x78, 0x6f, 0x5e, 0x8b, 0xe1, 0x01, 0xdc, 0x1c, 0x4b, 0x7c,
	0x8f, 0xe8, 0xff, 0x23, 0x14, 0x7e, 0x7f, 0xb8, 0x55, 0x82, 0x8b, 0xb2, 0x31, 0x51, 0xa3, 0xa4,
	0x91, 0xc4, 0xc3, 0xc7, 0xbe, 0xcd, 0x9f, 0xff, 0xbe, 0x01, 0x37, 0xe9, 0x33, 0xf2, 0x0c, 0xfc,
	0xf5, 0x51, 0xf2, 0xc3, 0x47, 0xa6, 0xbf, 0xd3, 0x59, 0x30, 0x0b, 0xfd, 0xe4, 0x64, 0x90, 0x00,
	0x16, 0x28, 0x3e, 0xb5, 0xd5, 0x5e, 0x28, 0x6a, 0x61, 0x7e, 0x6e, 0x91, 0x10, 0x1e, 0x6c, 0x64,
	0x6d, 0x14, 0xe3, 0xe6, 0x6d, 0x96, 0x29, 0xa1, 0x35, 0xb5, 0xb1, 0x75, 0x69, 0x93, 0x57, 0xf0,
	0x68, 0xd3, 0x56, 0xed, 0x91, 0x99, 0xf2, 0x87, 0xf8, 0xc0, 0xf4, 0x57, 0x2d, 0x32, 0xea, 0x60,
	0x77, 0x1a, 0x74, 0xed, 0x6d, 0x9e, 0x0b, 0x3e, 0x78, 0x9f, 0x55, 0xc9, 0x05, 0xbd, 0xe9, 0xdb,
	0x93, 0x80, 0x10, 0x70, 0xde, 0x2b, 0x59, 0xd1, 0x39, 0x16, 0xf0, 0x4c, 0x28, 0xb8, 0xe3, 0x2d,
	0x2e, 0xda, 0xa3, 0xec, 0x92, 0x9d, 0xde, 0x2a, 0x25, 0x15, 0xf5, 0x82, 0x59, 0xe8, 0x25, 0xa3,
	0x24, 0x2f, 0xc0, 0x89, 0x65, 0xa1, 0xa9, 0x1f, 0xd8, 0xe1, 0xe2, 0xf5, 0x93, 0x68, 0x44, 0x16,
	0x0d, 0xb8, 0xa2, 0x58, 0x16, 0x09, 0x56, 0xc8, 0x53, 0x98, 0x7f, 0x31, 0xcc, 0xb4, 0x9a, 0x02,
	0xbe, 0x7d, 0x50, 0xe4, 0x3e, 0x58, 0xa9, 0xa4, 0x0b, 0xf4, 0xac, 0x54, 0x76, 0x80, 0x52, 0xc5,
	0x6a, 0xcd, 0xb8, 0x29, 0x65, 0x8d, 0x98, 0xef, 0xf5, 0x80, 0x2e, 0x6c, 0xf2, 0x12, 0x1e, 0x9e,
	0x59, 0xbb, 0x3a, 0x13, 0x3f, 0xe9, 0x2d, 0x56, 0x27, 0xfe, 0xf2, 0x97, 0x05, 0x76, 0x2c, 0x8b,
	0xee, 0x57, 0x46, 0xec, 0xfd, 0x78, 0xa3, 0xfc, 0x77, 0x58, 0xeb, 0x3f, 0xc3, 0xda, 0xd3, 0x61,
	0x09, 0x38, 0xef, 0x98, 0x61, 0xc3, 0x42, 0x78, 0x26, 0x4b, 0xf0, 0x62, 0x59, 0xf4, 0x5f, 0xd6,
	0x6f, 0xf1, 0x57, 0x77, 0xf7, 0xa5, 0x65, 0x25, 0xb4, 0x61, 0x55, 0x83, 0x3b, 0x38, 0xc9, 0xc9,
	0xe8, 0x68, 0xa5, 0xb2, 0x29, 0xb9, 0xa6, 0x6e, 0x60, 0x77, 0xb4, 0x7a, 0x75, 0x8d, 0x8e, 0x77,
	0x77, 0x3a, 0xfe, 0x75, 0x3a, 0xeb, 0xc7, 0xdf, 0x88, 0x56, 0x7c, 0x75, 0x60, 0xf9, 0x81, 0xad,
	0xc6, 0x0d, 0xf7, 0x73, 0x3c, 0xbd, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0xca, 0xf7, 0xe9, 0x5e,
	0x18, 0x03, 0x00, 0x00,
}
